### ISSUE TITLE
Bug: Dependency issue when installing with Poetry

### ISSUE THREAD

**Issue by joseed-europeana** [europeana/rd-europeana-python-api#26]
@ejgenc There seem to be conflicts between the version of the dependencies. After executing the command `poetry install` I obtain the following message: 

```
Installing dependencies from lock file

  SolverProblemError

  The current project's Python requirement (3.7.3) is not compatible with some of the required packages Python requirement:
    - numpy requires Python >=3.8, so it will not be satisfied for Python 3.7.3

  Because no versions of pandas match >=1.3,<1.3.5 || >1.3.5,<2.0
   and pandas (1.3.5) depends on numpy (>=1.17.3), pandas (>=1.3,<2.0) requires numpy (>=1.17.3).
  Because numpy (1.22.3) requires Python >=3.8
   and no versions of numpy match >=1.17.3,<1.22.3 || >1.22.3, numpy is forbidden.
  Thus, pandas is forbidden.
  So, because pyeuropeana depends on pandas (^1.3), version solving failed.

  at ~/.local/share/pypoetry/venv/lib/python3.7/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For numpy, a possible solution would be to set the `python` property to "<empty>"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers

```

**Comment by ejgenc** [comment]
@joseed-europeana I am attaching the error message sent by Google Colab as the two errors might be related.

```
Installing collected packages: requests, pillow, fire, pyeuropeana
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Attempting uninstall: pillow
    Found existing installation: Pillow 7.1.2
    Uninstalling Pillow-7.1.2:
      Successfully uninstalled Pillow-7.1.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed fire-0.4.0 pillow-9.0.1 pyeuropeana-0.1.7 requests-2.27.1
WARNING: The following packages were previously imported in this runtime:
  [PIL]
You must restart the runtime in order to use newly installed versions.
```

**Comment by ejgenc** [comment]
@joseed-europeana I could install the project & the pre-commit hooks without problem on my Windows 10 machine. I sourced a fresh Poetry installation, got a fresh copy of the "master" branch and followed the contribution guide. Can you share a little bit more details?  Did you try installing on the R&D-3 server, or on your own machine?

**Comment by ejgenc** [comment]
@joseed-europeana I was also able to install a development version from the "master" branch into another folder in the R&D-3 server.  I was able to install pre-commit hooks and run tests locally. Could it be that you attempted testing the project in a moment in time when it was broken, but it no longer is?

**Comment by ejgenc** [comment]
@joseed-europeana Perhaps taking the steps that I describe below while on the R&D-3 server can solve your problems. They are aimed at wiping clean your Poetry install so that we start from scratch.

1.) cd to the root of the folder that is reserved for your on the server.
2.) Run the command `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --uninstall`. This will delete the Poetry CLI and its associated files.
3.) Locate the `.cache` folder found in the root of your reserved space on the server. There should be a file akin to `pypoetry` or `pythonpoetry`. Delete that folder
4.) We can now install Poetry again. Run the following command: `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - `
5.) If you haven't done already, open the `.bashrc` file located at your home folder and add these lines to it: `export PATH="$HOME/.poetry/bin:$PATH"`
6.) Check to see if Poetry is installed by running `poetry --version`
6.) We also need to delete any PyEuropeana files found on your home folder. I don't know what you have, but you can delete everything related to the project since we'll be cloning the repo again.
7.) Run the `git clone https://github.com/europeana/rd-europeana-python-api.git` command. You can run this your home directory, or in any sub-folder you want.
8.) `cd` to the newly cloned directory.
9.) First run `poetry shell`, then run `poetry install` to install project dependencies.
10.) You can then run `poetry run pre-commit install` and `poetry run pytest` to see if the environment works.

Let me know if any problems occur.

**Comment by ejgenc** [comment]
Closing this issue since it is solved. The steps above will be added to `CONTRIBUTING.md` in some form.

**Comment by joseed-europeana** [comment]
It can be closed, thanks a lot!
